---
version: "2"
formatters:
  enable:
    - gci
    - gofumpt
linters:
  enable:
    - durationcheck
    - errcheck
    - loggercheck
    - mirror
    - promlinter
    - reassign
    - unconvert
    - usestdlibvars
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
        - "-SA4011"
        - "-ST*"
